http:
  port: 8080

admin:
  port: 9876
  host: localhost

apiEndpoints:
  api:
    host: localhost
    paths: '/ip'
  products:
    host: localhost
    methods: 'GET, POST, PUT'
    paths: '/products*'
  orders:
    host: localhost
    methods: 'GET, POST, PUT'
    paths: '/orders*'
  payments:
    host: localhost
    methods: 'GET, POST, PUT'
    paths: '/payments*'

serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'
  productService:
    url: 'http://localhost:5003'
  orderService:
    url: 'http://localhost:5001'
  paymentService:
    url: 'http://localhost:5002'

policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit

pipelines:
  default:
    apiEndpoints:
      - api
    policies:
      - proxy:
          - action:
              serviceEndpoint: httpbin
              changeOrigin: true

  products:
    apiEndpoints:
      - products
    policies:
      - proxy:
          - action:
              serviceEndpoint: productService
              changeOrigin: true

  orders:
    apiEndpoints:
      - orders
    policies:
      - proxy:
          - action:
              serviceEndpoint: orderService
              changeOrigin: true

  payments:
    apiEndpoints:
      - payments
    policies:
      - proxy:
          - action:
              serviceEndpoint: paymentService
              changeOrigin: true
